/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
 * Generated on: 26-Feb-2025 23:04:24
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 128
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   uint32 filter coefficients.
 */
const int BL = 128;
const uint32_T B[128] = {
        247947,      769347,     1719592,     3060166,     4502884,     5417905,
       4842781,     1632410,           0,           0,           0,           0,
             0,           0,           0,           0,           0,           0,
             0,     9375377,    27794364,    35581343,    31515859,    17608214,
             0,           0,           0,           0,           0,           0,
      14221567,    26514252,    28889506,    20385977,     4022201,           0,
             0,           0,           0,           0,    16764061,    31111195,
      33664658,    22554468,     1230523,           0,           0,           0,
             0,     2472774,    33331061,    54418908,    55304592,    32082021,
             0,           0,           0,           0,           0,    34894879,
     150478000,   273330885,   376057962,   434480361,   434480361,   376057962,
     273330885,   150478000,    34894879,           0,           0,           0,
             0,           0,    32082021,    55304592,    54418908,    33331061,
       2472774,           0,           0,           0,           0,     1230523,
      22554468,    33664658,    31111195,    16764061,           0,           0,
             0,           0,           0,     4022201,    20385977,    28889506,
      26514252,    14221567,           0,           0,           0,           0,
             0,           0,    17608214,    31515859,    35581343,    27794364,
       9375377,           0,           0,           0,           0,           0,
             0,           0,           0,           0,           0,           0,
       1632410,     4842781,     5417905,     4502884,     3060166,     1719592,
        769347,      247947
};
