// -------------------------------------------------------------
// 
// File Name: C:\Users\nievep\Downloads\Advanced VLSI Design\Project 1\REPO\Advanced-VLSI-Project-REPO\Project 1\MatlabFilterCalculation\codegen\LowpassFilter\hdlsrc\Filter.v
// Created: 2025-02-25 23:37:05
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter
// Source Path: LowpassFilter/dsphdl.FIRFilter/Filter
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Filter
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  input   syncReset;
  output  signed [34:0] dataOut;  // sfix35_En32
  output  validOut;


  reg  dinRegVld;
  reg signed [15:0] dinReg_0_re;  // sfix16_En15
  reg signed [15:0] dinReg2_0_re;  // sfix16_En15
  wire signed [15:0] CoefOut_0;  // sfix16_En17
  wire signed [15:0] CoefOut_1;  // sfix16_En17
  wire signed [15:0] CoefOut_2;  // sfix16_En17
  wire signed [15:0] CoefOut_3;  // sfix16_En17
  wire signed [15:0] CoefOut_4;  // sfix16_En17
  wire signed [15:0] CoefOut_5;  // sfix16_En17
  wire signed [15:0] CoefOut_6;  // sfix16_En17
  wire signed [15:0] CoefOut_7;  // sfix16_En17
  wire signed [15:0] CoefOut_8;  // sfix16_En17
  wire signed [15:0] CoefOut_9;  // sfix16_En17
  wire signed [15:0] CoefOut_10;  // sfix16_En17
  wire signed [15:0] CoefOut_11;  // sfix16_En17
  wire signed [15:0] CoefOut_12;  // sfix16_En17
  wire signed [15:0] CoefOut_13;  // sfix16_En17
  wire signed [15:0] CoefOut_14;  // sfix16_En17
  wire signed [15:0] CoefOut_15;  // sfix16_En17
  wire signed [15:0] CoefOut_16;  // sfix16_En17
  wire signed [15:0] CoefOut_17;  // sfix16_En17
  wire signed [15:0] CoefOut_18;  // sfix16_En17
  wire signed [15:0] CoefOut_19;  // sfix16_En17
  wire signed [15:0] CoefOut_20;  // sfix16_En17
  wire signed [15:0] CoefOut_21;  // sfix16_En17
  wire signed [15:0] CoefOut_22;  // sfix16_En17
  wire signed [15:0] CoefOut_23;  // sfix16_En17
  wire signed [15:0] CoefOut_24;  // sfix16_En17
  wire signed [15:0] CoefOut_25;  // sfix16_En17
  wire signed [15:0] CoefOut_26;  // sfix16_En17
  wire signed [15:0] CoefOut_27;  // sfix16_En17
  wire signed [15:0] CoefOut_28;  // sfix16_En17
  wire signed [15:0] CoefOut_29;  // sfix16_En17
  wire signed [15:0] CoefOut_30;  // sfix16_En17
  wire signed [15:0] CoefOut_31;  // sfix16_En17
  wire signed [15:0] CoefOut_32;  // sfix16_En17
  wire signed [15:0] CoefOut_33;  // sfix16_En17
  wire signed [15:0] CoefOut_34;  // sfix16_En17
  wire signed [15:0] CoefOut_35;  // sfix16_En17
  wire signed [15:0] CoefOut_36;  // sfix16_En17
  wire signed [15:0] CoefOut_37;  // sfix16_En17
  wire signed [15:0] CoefOut_38;  // sfix16_En17
  wire signed [15:0] CoefOut_39;  // sfix16_En17
  wire signed [15:0] CoefOut_40;  // sfix16_En17
  wire signed [15:0] CoefOut_41;  // sfix16_En17
  wire signed [15:0] CoefOut_42;  // sfix16_En17
  wire signed [15:0] CoefOut_43;  // sfix16_En17
  wire signed [15:0] CoefOut_44;  // sfix16_En17
  wire signed [15:0] CoefOut_45;  // sfix16_En17
  wire signed [15:0] CoefOut_46;  // sfix16_En17
  wire signed [15:0] CoefOut_47;  // sfix16_En17
  wire signed [15:0] CoefOut_48;  // sfix16_En17
  wire signed [15:0] CoefOut_49;  // sfix16_En17
  wire signed [15:0] CoefOut_50;  // sfix16_En17
  wire signed [15:0] CoefOut_51;  // sfix16_En17
  wire signed [15:0] CoefOut_52;  // sfix16_En17
  wire signed [15:0] CoefOut_53;  // sfix16_En17
  wire signed [15:0] CoefOut_54;  // sfix16_En17
  wire signed [15:0] CoefOut_55;  // sfix16_En17
  wire signed [15:0] CoefOut_56;  // sfix16_En17
  wire signed [15:0] CoefOut_57;  // sfix16_En17
  wire signed [15:0] CoefOut_58;  // sfix16_En17
  wire signed [15:0] CoefOut_59;  // sfix16_En17
  wire signed [15:0] CoefOut_60;  // sfix16_En17
  wire signed [15:0] CoefOut_61;  // sfix16_En17
  wire signed [15:0] CoefOut_62;  // sfix16_En17
  wire signed [15:0] CoefOut_63;  // sfix16_En17
  wire signed [15:0] CoefOut_64;  // sfix16_En17
  wire signed [15:0] CoefOut_65;  // sfix16_En17
  wire signed [15:0] CoefOut_66;  // sfix16_En17
  wire signed [15:0] CoefOut_67;  // sfix16_En17
  wire signed [15:0] CoefOut_68;  // sfix16_En17
  wire signed [15:0] CoefOut_69;  // sfix16_En17
  wire signed [15:0] CoefOut_70;  // sfix16_En17
  wire signed [15:0] CoefOut_71;  // sfix16_En17
  wire signed [15:0] CoefOut_72;  // sfix16_En17
  wire signed [15:0] CoefOut_73;  // sfix16_En17
  wire signed [15:0] CoefOut_74;  // sfix16_En17
  wire signed [15:0] CoefOut_75;  // sfix16_En17
  wire signed [15:0] CoefOut_76;  // sfix16_En17
  wire signed [15:0] CoefOut_77;  // sfix16_En17
  wire signed [15:0] CoefOut_78;  // sfix16_En17
  wire signed [15:0] CoefOut_79;  // sfix16_En17
  wire signed [15:0] CoefOut_80;  // sfix16_En17
  wire signed [15:0] CoefOut_81;  // sfix16_En17
  wire signed [15:0] CoefOut_82;  // sfix16_En17
  wire signed [15:0] CoefOut_83;  // sfix16_En17
  wire signed [15:0] CoefOut_84;  // sfix16_En17
  wire signed [15:0] CoefOut_85;  // sfix16_En17
  wire signed [15:0] CoefOut_86;  // sfix16_En17
  wire signed [15:0] CoefOut_87;  // sfix16_En17
  wire signed [15:0] CoefOut_88;  // sfix16_En17
  wire signed [15:0] CoefOut_89;  // sfix16_En17
  wire signed [15:0] CoefOut_90;  // sfix16_En17
  wire signed [15:0] CoefOut_91;  // sfix16_En17
  wire signed [15:0] CoefOut_92;  // sfix16_En17
  wire signed [15:0] CoefOut_93;  // sfix16_En17
  wire signed [15:0] CoefOut_94;  // sfix16_En17
  wire signed [15:0] CoefOut_95;  // sfix16_En17
  wire signed [15:0] CoefOut_96;  // sfix16_En17
  wire signed [15:0] CoefOut_97;  // sfix16_En17
  wire signed [15:0] CoefOut_98;  // sfix16_En17
  wire signed [15:0] CoefOut_99;  // sfix16_En17
  wire signed [15:0] CoefOut_100;  // sfix16_En17
  reg  dinReg2Vld;
  wire signed [34:0] dout_1_re;  // sfix35_En32
  wire doutVld;


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinReg_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn;
            end
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinReg2_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end

  FilterCoef u_CoefTable_1 (.validIn(validIn),
                            .syncReset(syncReset),
                            .CoefOut_0(CoefOut_0),  // sfix16_En17
                            .CoefOut_1(CoefOut_1),  // sfix16_En17
                            .CoefOut_2(CoefOut_2),  // sfix16_En17
                            .CoefOut_3(CoefOut_3),  // sfix16_En17
                            .CoefOut_4(CoefOut_4),  // sfix16_En17
                            .CoefOut_5(CoefOut_5),  // sfix16_En17
                            .CoefOut_6(CoefOut_6),  // sfix16_En17
                            .CoefOut_7(CoefOut_7),  // sfix16_En17
                            .CoefOut_8(CoefOut_8),  // sfix16_En17
                            .CoefOut_9(CoefOut_9),  // sfix16_En17
                            .CoefOut_10(CoefOut_10),  // sfix16_En17
                            .CoefOut_11(CoefOut_11),  // sfix16_En17
                            .CoefOut_12(CoefOut_12),  // sfix16_En17
                            .CoefOut_13(CoefOut_13),  // sfix16_En17
                            .CoefOut_14(CoefOut_14),  // sfix16_En17
                            .CoefOut_15(CoefOut_15),  // sfix16_En17
                            .CoefOut_16(CoefOut_16),  // sfix16_En17
                            .CoefOut_17(CoefOut_17),  // sfix16_En17
                            .CoefOut_18(CoefOut_18),  // sfix16_En17
                            .CoefOut_19(CoefOut_19),  // sfix16_En17
                            .CoefOut_20(CoefOut_20),  // sfix16_En17
                            .CoefOut_21(CoefOut_21),  // sfix16_En17
                            .CoefOut_22(CoefOut_22),  // sfix16_En17
                            .CoefOut_23(CoefOut_23),  // sfix16_En17
                            .CoefOut_24(CoefOut_24),  // sfix16_En17
                            .CoefOut_25(CoefOut_25),  // sfix16_En17
                            .CoefOut_26(CoefOut_26),  // sfix16_En17
                            .CoefOut_27(CoefOut_27),  // sfix16_En17
                            .CoefOut_28(CoefOut_28),  // sfix16_En17
                            .CoefOut_29(CoefOut_29),  // sfix16_En17
                            .CoefOut_30(CoefOut_30),  // sfix16_En17
                            .CoefOut_31(CoefOut_31),  // sfix16_En17
                            .CoefOut_32(CoefOut_32),  // sfix16_En17
                            .CoefOut_33(CoefOut_33),  // sfix16_En17
                            .CoefOut_34(CoefOut_34),  // sfix16_En17
                            .CoefOut_35(CoefOut_35),  // sfix16_En17
                            .CoefOut_36(CoefOut_36),  // sfix16_En17
                            .CoefOut_37(CoefOut_37),  // sfix16_En17
                            .CoefOut_38(CoefOut_38),  // sfix16_En17
                            .CoefOut_39(CoefOut_39),  // sfix16_En17
                            .CoefOut_40(CoefOut_40),  // sfix16_En17
                            .CoefOut_41(CoefOut_41),  // sfix16_En17
                            .CoefOut_42(CoefOut_42),  // sfix16_En17
                            .CoefOut_43(CoefOut_43),  // sfix16_En17
                            .CoefOut_44(CoefOut_44),  // sfix16_En17
                            .CoefOut_45(CoefOut_45),  // sfix16_En17
                            .CoefOut_46(CoefOut_46),  // sfix16_En17
                            .CoefOut_47(CoefOut_47),  // sfix16_En17
                            .CoefOut_48(CoefOut_48),  // sfix16_En17
                            .CoefOut_49(CoefOut_49),  // sfix16_En17
                            .CoefOut_50(CoefOut_50),  // sfix16_En17
                            .CoefOut_51(CoefOut_51),  // sfix16_En17
                            .CoefOut_52(CoefOut_52),  // sfix16_En17
                            .CoefOut_53(CoefOut_53),  // sfix16_En17
                            .CoefOut_54(CoefOut_54),  // sfix16_En17
                            .CoefOut_55(CoefOut_55),  // sfix16_En17
                            .CoefOut_56(CoefOut_56),  // sfix16_En17
                            .CoefOut_57(CoefOut_57),  // sfix16_En17
                            .CoefOut_58(CoefOut_58),  // sfix16_En17
                            .CoefOut_59(CoefOut_59),  // sfix16_En17
                            .CoefOut_60(CoefOut_60),  // sfix16_En17
                            .CoefOut_61(CoefOut_61),  // sfix16_En17
                            .CoefOut_62(CoefOut_62),  // sfix16_En17
                            .CoefOut_63(CoefOut_63),  // sfix16_En17
                            .CoefOut_64(CoefOut_64),  // sfix16_En17
                            .CoefOut_65(CoefOut_65),  // sfix16_En17
                            .CoefOut_66(CoefOut_66),  // sfix16_En17
                            .CoefOut_67(CoefOut_67),  // sfix16_En17
                            .CoefOut_68(CoefOut_68),  // sfix16_En17
                            .CoefOut_69(CoefOut_69),  // sfix16_En17
                            .CoefOut_70(CoefOut_70),  // sfix16_En17
                            .CoefOut_71(CoefOut_71),  // sfix16_En17
                            .CoefOut_72(CoefOut_72),  // sfix16_En17
                            .CoefOut_73(CoefOut_73),  // sfix16_En17
                            .CoefOut_74(CoefOut_74),  // sfix16_En17
                            .CoefOut_75(CoefOut_75),  // sfix16_En17
                            .CoefOut_76(CoefOut_76),  // sfix16_En17
                            .CoefOut_77(CoefOut_77),  // sfix16_En17
                            .CoefOut_78(CoefOut_78),  // sfix16_En17
                            .CoefOut_79(CoefOut_79),  // sfix16_En17
                            .CoefOut_80(CoefOut_80),  // sfix16_En17
                            .CoefOut_81(CoefOut_81),  // sfix16_En17
                            .CoefOut_82(CoefOut_82),  // sfix16_En17
                            .CoefOut_83(CoefOut_83),  // sfix16_En17
                            .CoefOut_84(CoefOut_84),  // sfix16_En17
                            .CoefOut_85(CoefOut_85),  // sfix16_En17
                            .CoefOut_86(CoefOut_86),  // sfix16_En17
                            .CoefOut_87(CoefOut_87),  // sfix16_En17
                            .CoefOut_88(CoefOut_88),  // sfix16_En17
                            .CoefOut_89(CoefOut_89),  // sfix16_En17
                            .CoefOut_90(CoefOut_90),  // sfix16_En17
                            .CoefOut_91(CoefOut_91),  // sfix16_En17
                            .CoefOut_92(CoefOut_92),  // sfix16_En17
                            .CoefOut_93(CoefOut_93),  // sfix16_En17
                            .CoefOut_94(CoefOut_94),  // sfix16_En17
                            .CoefOut_95(CoefOut_95),  // sfix16_En17
                            .CoefOut_96(CoefOut_96),  // sfix16_En17
                            .CoefOut_97(CoefOut_97),  // sfix16_En17
                            .CoefOut_98(CoefOut_98),  // sfix16_En17
                            .CoefOut_99(CoefOut_99),  // sfix16_En17
                            .CoefOut_100(CoefOut_100)  // sfix16_En17
                            );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end

  subFilter u_subFilter_1_re (.clk(clk),
                              .reset(reset),
                              .enb(enb),
                              .dinReg2_0_re(dinReg2_0_re),  // sfix16_En15
                              .coefIn_0(CoefOut_0),  // sfix16_En17
                              .coefIn_1(CoefOut_1),  // sfix16_En17
                              .coefIn_2(CoefOut_2),  // sfix16_En17
                              .coefIn_3(CoefOut_3),  // sfix16_En17
                              .coefIn_4(CoefOut_4),  // sfix16_En17
                              .coefIn_5(CoefOut_5),  // sfix16_En17
                              .coefIn_6(CoefOut_6),  // sfix16_En17
                              .coefIn_7(CoefOut_7),  // sfix16_En17
                              .coefIn_8(CoefOut_8),  // sfix16_En17
                              .coefIn_9(CoefOut_9),  // sfix16_En17
                              .coefIn_10(CoefOut_10),  // sfix16_En17
                              .coefIn_11(CoefOut_11),  // sfix16_En17
                              .coefIn_12(CoefOut_12),  // sfix16_En17
                              .coefIn_13(CoefOut_13),  // sfix16_En17
                              .coefIn_14(CoefOut_14),  // sfix16_En17
                              .coefIn_15(CoefOut_15),  // sfix16_En17
                              .coefIn_16(CoefOut_16),  // sfix16_En17
                              .coefIn_17(CoefOut_17),  // sfix16_En17
                              .coefIn_18(CoefOut_18),  // sfix16_En17
                              .coefIn_19(CoefOut_19),  // sfix16_En17
                              .coefIn_20(CoefOut_20),  // sfix16_En17
                              .coefIn_21(CoefOut_21),  // sfix16_En17
                              .coefIn_22(CoefOut_22),  // sfix16_En17
                              .coefIn_23(CoefOut_23),  // sfix16_En17
                              .coefIn_24(CoefOut_24),  // sfix16_En17
                              .coefIn_25(CoefOut_25),  // sfix16_En17
                              .coefIn_26(CoefOut_26),  // sfix16_En17
                              .coefIn_27(CoefOut_27),  // sfix16_En17
                              .coefIn_28(CoefOut_28),  // sfix16_En17
                              .coefIn_29(CoefOut_29),  // sfix16_En17
                              .coefIn_30(CoefOut_30),  // sfix16_En17
                              .coefIn_31(CoefOut_31),  // sfix16_En17
                              .coefIn_32(CoefOut_32),  // sfix16_En17
                              .coefIn_33(CoefOut_33),  // sfix16_En17
                              .coefIn_34(CoefOut_34),  // sfix16_En17
                              .coefIn_35(CoefOut_35),  // sfix16_En17
                              .coefIn_36(CoefOut_36),  // sfix16_En17
                              .coefIn_37(CoefOut_37),  // sfix16_En17
                              .coefIn_38(CoefOut_38),  // sfix16_En17
                              .coefIn_39(CoefOut_39),  // sfix16_En17
                              .coefIn_40(CoefOut_40),  // sfix16_En17
                              .coefIn_41(CoefOut_41),  // sfix16_En17
                              .coefIn_42(CoefOut_42),  // sfix16_En17
                              .coefIn_43(CoefOut_43),  // sfix16_En17
                              .coefIn_44(CoefOut_44),  // sfix16_En17
                              .coefIn_45(CoefOut_45),  // sfix16_En17
                              .coefIn_46(CoefOut_46),  // sfix16_En17
                              .coefIn_47(CoefOut_47),  // sfix16_En17
                              .coefIn_48(CoefOut_48),  // sfix16_En17
                              .coefIn_49(CoefOut_49),  // sfix16_En17
                              .coefIn_50(CoefOut_50),  // sfix16_En17
                              .coefIn_51(CoefOut_51),  // sfix16_En17
                              .coefIn_52(CoefOut_52),  // sfix16_En17
                              .coefIn_53(CoefOut_53),  // sfix16_En17
                              .coefIn_54(CoefOut_54),  // sfix16_En17
                              .coefIn_55(CoefOut_55),  // sfix16_En17
                              .coefIn_56(CoefOut_56),  // sfix16_En17
                              .coefIn_57(CoefOut_57),  // sfix16_En17
                              .coefIn_58(CoefOut_58),  // sfix16_En17
                              .coefIn_59(CoefOut_59),  // sfix16_En17
                              .coefIn_60(CoefOut_60),  // sfix16_En17
                              .coefIn_61(CoefOut_61),  // sfix16_En17
                              .coefIn_62(CoefOut_62),  // sfix16_En17
                              .coefIn_63(CoefOut_63),  // sfix16_En17
                              .coefIn_64(CoefOut_64),  // sfix16_En17
                              .coefIn_65(CoefOut_65),  // sfix16_En17
                              .coefIn_66(CoefOut_66),  // sfix16_En17
                              .coefIn_67(CoefOut_67),  // sfix16_En17
                              .coefIn_68(CoefOut_68),  // sfix16_En17
                              .coefIn_69(CoefOut_69),  // sfix16_En17
                              .coefIn_70(CoefOut_70),  // sfix16_En17
                              .coefIn_71(CoefOut_71),  // sfix16_En17
                              .coefIn_72(CoefOut_72),  // sfix16_En17
                              .coefIn_73(CoefOut_73),  // sfix16_En17
                              .coefIn_74(CoefOut_74),  // sfix16_En17
                              .coefIn_75(CoefOut_75),  // sfix16_En17
                              .coefIn_76(CoefOut_76),  // sfix16_En17
                              .coefIn_77(CoefOut_77),  // sfix16_En17
                              .coefIn_78(CoefOut_78),  // sfix16_En17
                              .coefIn_79(CoefOut_79),  // sfix16_En17
                              .coefIn_80(CoefOut_80),  // sfix16_En17
                              .coefIn_81(CoefOut_81),  // sfix16_En17
                              .coefIn_82(CoefOut_82),  // sfix16_En17
                              .coefIn_83(CoefOut_83),  // sfix16_En17
                              .coefIn_84(CoefOut_84),  // sfix16_En17
                              .coefIn_85(CoefOut_85),  // sfix16_En17
                              .coefIn_86(CoefOut_86),  // sfix16_En17
                              .coefIn_87(CoefOut_87),  // sfix16_En17
                              .coefIn_88(CoefOut_88),  // sfix16_En17
                              .coefIn_89(CoefOut_89),  // sfix16_En17
                              .coefIn_90(CoefOut_90),  // sfix16_En17
                              .coefIn_91(CoefOut_91),  // sfix16_En17
                              .coefIn_92(CoefOut_92),  // sfix16_En17
                              .coefIn_93(CoefOut_93),  // sfix16_En17
                              .coefIn_94(CoefOut_94),  // sfix16_En17
                              .coefIn_95(CoefOut_95),  // sfix16_En17
                              .coefIn_96(CoefOut_96),  // sfix16_En17
                              .coefIn_97(CoefOut_97),  // sfix16_En17
                              .coefIn_98(CoefOut_98),  // sfix16_En17
                              .coefIn_99(CoefOut_99),  // sfix16_En17
                              .coefIn_100(CoefOut_100),  // sfix16_En17
                              .dinRegVld(dinReg2Vld),
                              .syncReset(syncReset),
                              .dout_1_re(dout_1_re),  // sfix35_En32
                              .doutVld(doutVld)
                              );

  assign dataOut = dout_1_re;

  assign validOut = doutVld;

endmodule  // Filter

