// -------------------------------------------------------------
// 
// File Name: C:\Users\nievep\Downloads\Advanced VLSI Design\Project 1\REPO\Advanced-VLSI-Project-REPO\Project 1\MatlabFilterCalculation\codegen\LowpassFilter\hdlsrc\dsphdl_FIRFilter.v
// Created: 2025-02-25 23:37:05
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dsphdl_FIRFilter
// Source Path: LowpassFilter/dsphdl.FIRFilter
// Hierarchy Level: 1
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dsphdl_FIRFilter
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  signed [34:0] dataOut;  // sfix35_En32
  output  validOut;


  wire syncReset;


  assign syncReset = 1'b0;

  Filter u_FilterBank (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .dataIn(dataIn),  // sfix16_En15
                       .validIn(validIn),
                       .syncReset(syncReset),
                       .dataOut(dataOut),  // sfix35_En32
                       .validOut(validOut)
                       );

endmodule  // dsphdl_FIRFilter

