// -------------------------------------------------------------
// 
// File Name: C:\Users\nievep\Downloads\Advanced VLSI Design\Project 1\REPO\Advanced-VLSI-Project-REPO\Project 1\MatlabFilterCalculation\codegen\LowpassFilter\hdlsrc\FilterCoef.v
// Created: 2025-02-25 23:37:05
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterCoef
// Source Path: LowpassFilter/dsphdl.FIRFilter/Filter/FilterCoef
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterCoef
          (validIn,
           syncReset,
           CoefOut_0,
           CoefOut_1,
           CoefOut_2,
           CoefOut_3,
           CoefOut_4,
           CoefOut_5,
           CoefOut_6,
           CoefOut_7,
           CoefOut_8,
           CoefOut_9,
           CoefOut_10,
           CoefOut_11,
           CoefOut_12,
           CoefOut_13,
           CoefOut_14,
           CoefOut_15,
           CoefOut_16,
           CoefOut_17,
           CoefOut_18,
           CoefOut_19,
           CoefOut_20,
           CoefOut_21,
           CoefOut_22,
           CoefOut_23,
           CoefOut_24,
           CoefOut_25,
           CoefOut_26,
           CoefOut_27,
           CoefOut_28,
           CoefOut_29,
           CoefOut_30,
           CoefOut_31,
           CoefOut_32,
           CoefOut_33,
           CoefOut_34,
           CoefOut_35,
           CoefOut_36,
           CoefOut_37,
           CoefOut_38,
           CoefOut_39,
           CoefOut_40,
           CoefOut_41,
           CoefOut_42,
           CoefOut_43,
           CoefOut_44,
           CoefOut_45,
           CoefOut_46,
           CoefOut_47,
           CoefOut_48,
           CoefOut_49,
           CoefOut_50,
           CoefOut_51,
           CoefOut_52,
           CoefOut_53,
           CoefOut_54,
           CoefOut_55,
           CoefOut_56,
           CoefOut_57,
           CoefOut_58,
           CoefOut_59,
           CoefOut_60,
           CoefOut_61,
           CoefOut_62,
           CoefOut_63,
           CoefOut_64,
           CoefOut_65,
           CoefOut_66,
           CoefOut_67,
           CoefOut_68,
           CoefOut_69,
           CoefOut_70,
           CoefOut_71,
           CoefOut_72,
           CoefOut_73,
           CoefOut_74,
           CoefOut_75,
           CoefOut_76,
           CoefOut_77,
           CoefOut_78,
           CoefOut_79,
           CoefOut_80,
           CoefOut_81,
           CoefOut_82,
           CoefOut_83,
           CoefOut_84,
           CoefOut_85,
           CoefOut_86,
           CoefOut_87,
           CoefOut_88,
           CoefOut_89,
           CoefOut_90,
           CoefOut_91,
           CoefOut_92,
           CoefOut_93,
           CoefOut_94,
           CoefOut_95,
           CoefOut_96,
           CoefOut_97,
           CoefOut_98,
           CoefOut_99,
           CoefOut_100);


  input   validIn;
  input   syncReset;
  output  signed [15:0] CoefOut_0;  // sfix16_En17
  output  signed [15:0] CoefOut_1;  // sfix16_En17
  output  signed [15:0] CoefOut_2;  // sfix16_En17
  output  signed [15:0] CoefOut_3;  // sfix16_En17
  output  signed [15:0] CoefOut_4;  // sfix16_En17
  output  signed [15:0] CoefOut_5;  // sfix16_En17
  output  signed [15:0] CoefOut_6;  // sfix16_En17
  output  signed [15:0] CoefOut_7;  // sfix16_En17
  output  signed [15:0] CoefOut_8;  // sfix16_En17
  output  signed [15:0] CoefOut_9;  // sfix16_En17
  output  signed [15:0] CoefOut_10;  // sfix16_En17
  output  signed [15:0] CoefOut_11;  // sfix16_En17
  output  signed [15:0] CoefOut_12;  // sfix16_En17
  output  signed [15:0] CoefOut_13;  // sfix16_En17
  output  signed [15:0] CoefOut_14;  // sfix16_En17
  output  signed [15:0] CoefOut_15;  // sfix16_En17
  output  signed [15:0] CoefOut_16;  // sfix16_En17
  output  signed [15:0] CoefOut_17;  // sfix16_En17
  output  signed [15:0] CoefOut_18;  // sfix16_En17
  output  signed [15:0] CoefOut_19;  // sfix16_En17
  output  signed [15:0] CoefOut_20;  // sfix16_En17
  output  signed [15:0] CoefOut_21;  // sfix16_En17
  output  signed [15:0] CoefOut_22;  // sfix16_En17
  output  signed [15:0] CoefOut_23;  // sfix16_En17
  output  signed [15:0] CoefOut_24;  // sfix16_En17
  output  signed [15:0] CoefOut_25;  // sfix16_En17
  output  signed [15:0] CoefOut_26;  // sfix16_En17
  output  signed [15:0] CoefOut_27;  // sfix16_En17
  output  signed [15:0] CoefOut_28;  // sfix16_En17
  output  signed [15:0] CoefOut_29;  // sfix16_En17
  output  signed [15:0] CoefOut_30;  // sfix16_En17
  output  signed [15:0] CoefOut_31;  // sfix16_En17
  output  signed [15:0] CoefOut_32;  // sfix16_En17
  output  signed [15:0] CoefOut_33;  // sfix16_En17
  output  signed [15:0] CoefOut_34;  // sfix16_En17
  output  signed [15:0] CoefOut_35;  // sfix16_En17
  output  signed [15:0] CoefOut_36;  // sfix16_En17
  output  signed [15:0] CoefOut_37;  // sfix16_En17
  output  signed [15:0] CoefOut_38;  // sfix16_En17
  output  signed [15:0] CoefOut_39;  // sfix16_En17
  output  signed [15:0] CoefOut_40;  // sfix16_En17
  output  signed [15:0] CoefOut_41;  // sfix16_En17
  output  signed [15:0] CoefOut_42;  // sfix16_En17
  output  signed [15:0] CoefOut_43;  // sfix16_En17
  output  signed [15:0] CoefOut_44;  // sfix16_En17
  output  signed [15:0] CoefOut_45;  // sfix16_En17
  output  signed [15:0] CoefOut_46;  // sfix16_En17
  output  signed [15:0] CoefOut_47;  // sfix16_En17
  output  signed [15:0] CoefOut_48;  // sfix16_En17
  output  signed [15:0] CoefOut_49;  // sfix16_En17
  output  signed [15:0] CoefOut_50;  // sfix16_En17
  output  signed [15:0] CoefOut_51;  // sfix16_En17
  output  signed [15:0] CoefOut_52;  // sfix16_En17
  output  signed [15:0] CoefOut_53;  // sfix16_En17
  output  signed [15:0] CoefOut_54;  // sfix16_En17
  output  signed [15:0] CoefOut_55;  // sfix16_En17
  output  signed [15:0] CoefOut_56;  // sfix16_En17
  output  signed [15:0] CoefOut_57;  // sfix16_En17
  output  signed [15:0] CoefOut_58;  // sfix16_En17
  output  signed [15:0] CoefOut_59;  // sfix16_En17
  output  signed [15:0] CoefOut_60;  // sfix16_En17
  output  signed [15:0] CoefOut_61;  // sfix16_En17
  output  signed [15:0] CoefOut_62;  // sfix16_En17
  output  signed [15:0] CoefOut_63;  // sfix16_En17
  output  signed [15:0] CoefOut_64;  // sfix16_En17
  output  signed [15:0] CoefOut_65;  // sfix16_En17
  output  signed [15:0] CoefOut_66;  // sfix16_En17
  output  signed [15:0] CoefOut_67;  // sfix16_En17
  output  signed [15:0] CoefOut_68;  // sfix16_En17
  output  signed [15:0] CoefOut_69;  // sfix16_En17
  output  signed [15:0] CoefOut_70;  // sfix16_En17
  output  signed [15:0] CoefOut_71;  // sfix16_En17
  output  signed [15:0] CoefOut_72;  // sfix16_En17
  output  signed [15:0] CoefOut_73;  // sfix16_En17
  output  signed [15:0] CoefOut_74;  // sfix16_En17
  output  signed [15:0] CoefOut_75;  // sfix16_En17
  output  signed [15:0] CoefOut_76;  // sfix16_En17
  output  signed [15:0] CoefOut_77;  // sfix16_En17
  output  signed [15:0] CoefOut_78;  // sfix16_En17
  output  signed [15:0] CoefOut_79;  // sfix16_En17
  output  signed [15:0] CoefOut_80;  // sfix16_En17
  output  signed [15:0] CoefOut_81;  // sfix16_En17
  output  signed [15:0] CoefOut_82;  // sfix16_En17
  output  signed [15:0] CoefOut_83;  // sfix16_En17
  output  signed [15:0] CoefOut_84;  // sfix16_En17
  output  signed [15:0] CoefOut_85;  // sfix16_En17
  output  signed [15:0] CoefOut_86;  // sfix16_En17
  output  signed [15:0] CoefOut_87;  // sfix16_En17
  output  signed [15:0] CoefOut_88;  // sfix16_En17
  output  signed [15:0] CoefOut_89;  // sfix16_En17
  output  signed [15:0] CoefOut_90;  // sfix16_En17
  output  signed [15:0] CoefOut_91;  // sfix16_En17
  output  signed [15:0] CoefOut_92;  // sfix16_En17
  output  signed [15:0] CoefOut_93;  // sfix16_En17
  output  signed [15:0] CoefOut_94;  // sfix16_En17
  output  signed [15:0] CoefOut_95;  // sfix16_En17
  output  signed [15:0] CoefOut_96;  // sfix16_En17
  output  signed [15:0] CoefOut_97;  // sfix16_En17
  output  signed [15:0] CoefOut_98;  // sfix16_En17
  output  signed [15:0] CoefOut_99;  // sfix16_En17
  output  signed [15:0] CoefOut_100;  // sfix16_En17


  wire signed [15:0] CoefData;  // sfix16_En17
  wire signed [15:0] CoefData_1;  // sfix16_En17
  wire signed [15:0] CoefData_2;  // sfix16_En17
  wire signed [15:0] CoefData_3;  // sfix16_En17
  wire signed [15:0] CoefData_4;  // sfix16_En17
  wire signed [15:0] CoefData_5;  // sfix16_En17
  wire signed [15:0] CoefData_6;  // sfix16_En17
  wire signed [15:0] CoefData_7;  // sfix16_En17
  wire signed [15:0] CoefData_8;  // sfix16_En17
  wire signed [15:0] CoefData_9;  // sfix16_En17
  wire signed [15:0] CoefData_10;  // sfix16_En17
  wire signed [15:0] CoefData_11;  // sfix16_En17
  wire signed [15:0] CoefData_12;  // sfix16_En17
  wire signed [15:0] CoefData_13;  // sfix16_En17
  wire signed [15:0] CoefData_14;  // sfix16_En17
  wire signed [15:0] CoefData_15;  // sfix16_En17
  wire signed [15:0] CoefData_16;  // sfix16_En17
  wire signed [15:0] CoefData_17;  // sfix16_En17
  wire signed [15:0] CoefData_18;  // sfix16_En17
  wire signed [15:0] CoefData_19;  // sfix16_En17
  wire signed [15:0] CoefData_20;  // sfix16_En17
  wire signed [15:0] CoefData_21;  // sfix16_En17
  wire signed [15:0] CoefData_22;  // sfix16_En17
  wire signed [15:0] CoefData_23;  // sfix16_En17
  wire signed [15:0] CoefData_24;  // sfix16_En17
  wire signed [15:0] CoefData_25;  // sfix16_En17
  wire signed [15:0] CoefData_26;  // sfix16_En17
  wire signed [15:0] CoefData_27;  // sfix16_En17
  wire signed [15:0] CoefData_28;  // sfix16_En17
  wire signed [15:0] CoefData_29;  // sfix16_En17
  wire signed [15:0] CoefData_30;  // sfix16_En17
  wire signed [15:0] CoefData_31;  // sfix16_En17
  wire signed [15:0] CoefData_32;  // sfix16_En17
  wire signed [15:0] CoefData_33;  // sfix16_En17
  wire signed [15:0] CoefData_34;  // sfix16_En17
  wire signed [15:0] CoefData_35;  // sfix16_En17
  wire signed [15:0] CoefData_36;  // sfix16_En17
  wire signed [15:0] CoefData_37;  // sfix16_En17
  wire signed [15:0] CoefData_38;  // sfix16_En17
  wire signed [15:0] CoefData_39;  // sfix16_En17
  wire signed [15:0] CoefData_40;  // sfix16_En17
  wire signed [15:0] CoefData_41;  // sfix16_En17
  wire signed [15:0] CoefData_42;  // sfix16_En17
  wire signed [15:0] CoefData_43;  // sfix16_En17
  wire signed [15:0] CoefData_44;  // sfix16_En17
  wire signed [15:0] CoefData_45;  // sfix16_En17
  wire signed [15:0] CoefData_46;  // sfix16_En17
  wire signed [15:0] CoefData_47;  // sfix16_En17
  wire signed [15:0] CoefData_48;  // sfix16_En17
  wire signed [15:0] CoefData_49;  // sfix16_En17
  wire signed [15:0] CoefData_50;  // sfix16_En17
  wire signed [15:0] CoefData_51;  // sfix16_En17
  wire signed [15:0] CoefData_52;  // sfix16_En17
  wire signed [15:0] CoefData_53;  // sfix16_En17
  wire signed [15:0] CoefData_54;  // sfix16_En17
  wire signed [15:0] CoefData_55;  // sfix16_En17
  wire signed [15:0] CoefData_56;  // sfix16_En17
  wire signed [15:0] CoefData_57;  // sfix16_En17
  wire signed [15:0] CoefData_58;  // sfix16_En17
  wire signed [15:0] CoefData_59;  // sfix16_En17
  wire signed [15:0] CoefData_60;  // sfix16_En17
  wire signed [15:0] CoefData_61;  // sfix16_En17
  wire signed [15:0] CoefData_62;  // sfix16_En17
  wire signed [15:0] CoefData_63;  // sfix16_En17
  wire signed [15:0] CoefData_64;  // sfix16_En17
  wire signed [15:0] CoefData_65;  // sfix16_En17
  wire signed [15:0] CoefData_66;  // sfix16_En17
  wire signed [15:0] CoefData_67;  // sfix16_En17
  wire signed [15:0] CoefData_68;  // sfix16_En17
  wire signed [15:0] CoefData_69;  // sfix16_En17
  wire signed [15:0] CoefData_70;  // sfix16_En17
  wire signed [15:0] CoefData_71;  // sfix16_En17
  wire signed [15:0] CoefData_72;  // sfix16_En17
  wire signed [15:0] CoefData_73;  // sfix16_En17
  wire signed [15:0] CoefData_74;  // sfix16_En17
  wire signed [15:0] CoefData_75;  // sfix16_En17
  wire signed [15:0] CoefData_76;  // sfix16_En17
  wire signed [15:0] CoefData_77;  // sfix16_En17
  wire signed [15:0] CoefData_78;  // sfix16_En17
  wire signed [15:0] CoefData_79;  // sfix16_En17
  wire signed [15:0] CoefData_80;  // sfix16_En17
  wire signed [15:0] CoefData_81;  // sfix16_En17
  wire signed [15:0] CoefData_82;  // sfix16_En17
  wire signed [15:0] CoefData_83;  // sfix16_En17
  wire signed [15:0] CoefData_84;  // sfix16_En17
  wire signed [15:0] CoefData_85;  // sfix16_En17
  wire signed [15:0] CoefData_86;  // sfix16_En17
  wire signed [15:0] CoefData_87;  // sfix16_En17
  wire signed [15:0] CoefData_88;  // sfix16_En17
  wire signed [15:0] CoefData_89;  // sfix16_En17
  wire signed [15:0] CoefData_90;  // sfix16_En17
  wire signed [15:0] CoefData_91;  // sfix16_En17
  wire signed [15:0] CoefData_92;  // sfix16_En17
  wire signed [15:0] CoefData_93;  // sfix16_En17
  wire signed [15:0] CoefData_94;  // sfix16_En17
  wire signed [15:0] CoefData_95;  // sfix16_En17
  wire signed [15:0] CoefData_96;  // sfix16_En17
  wire signed [15:0] CoefData_97;  // sfix16_En17
  wire signed [15:0] CoefData_98;  // sfix16_En17
  wire signed [15:0] CoefData_99;  // sfix16_En17
  wire signed [15:0] CoefData_100;  // sfix16_En17


  // CoefReg_1
  assign CoefData = 16'sb1111111111100100;

  assign CoefOut_0 = CoefData;

  // CoefReg_2
  assign CoefData_1 = 16'sb1111111110011100;

  assign CoefOut_1 = CoefData_1;

  // CoefReg_3
  assign CoefData_2 = 16'sb1111111100000111;

  assign CoefOut_2 = CoefData_2;

  // CoefReg_4
  assign CoefData_3 = 16'sb1111111000000111;

  assign CoefOut_3 = CoefData_3;

  // CoefReg_5
  assign CoefData_4 = 16'sb1111110010010011;

  assign CoefOut_4 = CoefData_4;

  // CoefReg_6
  assign CoefData_5 = 16'sb1111101011000011;

  assign CoefOut_5 = CoefData_5;

  // CoefReg_7
  assign CoefData_6 = 16'sb1111100011100000;

  assign CoefOut_6 = CoefData_6;

  // CoefReg_8
  assign CoefData_7 = 16'sb1111011101100101;

  assign CoefOut_7 = CoefData_7;

  // CoefReg_9
  assign CoefData_8 = 16'sb1111011011110010;

  assign CoefOut_8 = CoefData_8;

  // CoefReg_10
  assign CoefData_9 = 16'sb1111100000100111;

  assign CoefOut_9 = CoefData_9;

  // CoefReg_11
  assign CoefData_10 = 16'sb1111101101111010;

  assign CoefOut_10 = CoefData_10;

  // CoefReg_12
  assign CoefData_11 = 16'sb0000000100000001;

  assign CoefOut_11 = CoefData_11;

  // CoefReg_13
  assign CoefData_12 = 16'sb0000100001001100;

  assign CoefOut_12 = CoefData_12;

  // CoefReg_14
  assign CoefData_13 = 16'sb0001000001100001;

  assign CoefOut_13 = CoefData_13;

  // CoefReg_15
  assign CoefData_14 = 16'sb0001011111011011;

  assign CoefOut_14 = CoefData_14;

  // CoefReg_16
  assign CoefData_15 = 16'sb0001110100110100;

  assign CoefOut_15 = CoefData_15;

  // CoefReg_17
  assign CoefData_16 = 16'sb0001111100100101;

  assign CoefOut_16 = CoefData_16;

  // CoefReg_18
  assign CoefData_17 = 16'sb0001110100001001;

  assign CoefOut_17 = CoefData_17;

  // CoefReg_19
  assign CoefData_18 = 16'sb0001011100100011;

  assign CoefOut_18 = CoefData_18;

  // CoefReg_20
  assign CoefData_19 = 16'sb0000111010100100;

  assign CoefOut_19 = CoefData_19;

  // CoefReg_21
  assign CoefData_20 = 16'sb0000010101110100;

  assign CoefOut_20 = CoefData_20;

  // CoefReg_22
  assign CoefData_21 = 16'sb1111110110111100;

  assign CoefOut_21 = CoefData_21;

  // CoefReg_23
  assign CoefData_22 = 16'sb1111100101000111;

  assign CoefOut_22 = CoefData_22;

  // CoefReg_24
  assign CoefData_23 = 16'sb1111100100000001;

  assign CoefOut_23 = CoefData_23;

  // CoefReg_25
  assign CoefData_24 = 16'sb1111110010100010;

  assign CoefOut_24 = CoefData_24;

  // CoefReg_26
  assign CoefData_25 = 16'sb0000001010111000;

  assign CoefOut_25 = CoefData_25;

  // CoefReg_27
  assign CoefData_26 = 16'sb0000100100010000;

  assign CoefOut_26 = CoefData_26;

  // CoefReg_28
  assign CoefData_27 = 16'sb0000110101011111;

  assign CoefOut_27 = CoefData_27;

  // CoefReg_29
  assign CoefData_28 = 16'sb0000111000000011;

  assign CoefOut_28 = CoefData_28;

  // CoefReg_30
  assign CoefData_29 = 16'sb0000101010010110;

  assign CoefOut_29 = CoefData_29;

  // CoefReg_31
  assign CoefData_30 = 16'sb0000010000010110;

  assign CoefOut_30 = CoefData_30;

  // CoefReg_32
  assign CoefData_31 = 16'sb1111110010101001;

  assign CoefOut_31 = CoefData_31;

  // CoefReg_33
  assign CoefData_32 = 16'sb1111011011100010;

  assign CoefOut_32 = CoefData_32;

  // CoefReg_34
  assign CoefData_33 = 16'sb1111010011100111;

  assign CoefOut_33 = CoefData_33;

  // CoefReg_35
  assign CoefData_34 = 16'sb1111011110011100;

  assign CoefOut_34 = CoefData_34;

  // CoefReg_36
  assign CoefData_35 = 16'sb1111111000111110;

  assign CoefOut_35 = CoefData_35;

  // CoefReg_37
  assign CoefData_36 = 16'sb0000011010000011;

  assign CoefOut_36 = CoefData_36;

  // CoefReg_38
  assign CoefData_37 = 16'sb0000110101001101;

  assign CoefOut_37 = CoefData_37;

  // CoefReg_39
  assign CoefData_38 = 16'sb0000111110111000;

  assign CoefOut_38 = CoefData_38;

  // CoefReg_40
  assign CoefData_39 = 16'sb0000110000110001;

  assign CoefOut_39 = CoefData_39;

  // CoefReg_41
  assign CoefData_40 = 16'sb0000001100110011;

  assign CoefOut_40 = CoefData_40;

  // CoefReg_42
  assign CoefData_41 = 16'sb1111011101100111;

  assign CoefOut_41 = CoefData_41;

  // CoefReg_43
  assign CoefData_42 = 16'sb1110110100000101;

  assign CoefOut_42 = CoefData_42;

  // CoefReg_44
  assign CoefData_43 = 16'sb1110100010100001;

  assign CoefOut_43 = CoefData_43;

  // CoefReg_45
  assign CoefData_44 = 16'sb1110110110111011;

  assign CoefOut_44 = CoefData_44;

  // CoefReg_46
  assign CoefData_45 = 16'sb1111110110000010;

  assign CoefOut_45 = CoefData_45;

  // CoefReg_47
  assign CoefData_46 = 16'sb0001011000110010;

  assign CoefOut_46 = CoefData_46;

  // CoefReg_48
  assign CoefData_47 = 16'sb0011001101010010;

  assign CoefOut_47 = CoefData_47;

  // CoefReg_49
  assign CoefData_48 = 16'sb0100111011000000;

  assign CoefOut_48 = CoefData_48;

  // CoefReg_50
  assign CoefData_49 = 16'sb0110001001001001;

  assign CoefOut_49 = CoefData_49;

  // CoefReg_51
  assign CoefData_50 = 16'sb0110100101011100;

  assign CoefOut_50 = CoefData_50;

  // CoefReg_52
  assign CoefData_51 = 16'sb0110001001001001;

  assign CoefOut_51 = CoefData_51;

  // CoefReg_53
  assign CoefData_52 = 16'sb0100111011000000;

  assign CoefOut_52 = CoefData_52;

  // CoefReg_54
  assign CoefData_53 = 16'sb0011001101010010;

  assign CoefOut_53 = CoefData_53;

  // CoefReg_55
  assign CoefData_54 = 16'sb0001011000110010;

  assign CoefOut_54 = CoefData_54;

  // CoefReg_56
  assign CoefData_55 = 16'sb1111110110000010;

  assign CoefOut_55 = CoefData_55;

  // CoefReg_57
  assign CoefData_56 = 16'sb1110110110111011;

  assign CoefOut_56 = CoefData_56;

  // CoefReg_58
  assign CoefData_57 = 16'sb1110100010100001;

  assign CoefOut_57 = CoefData_57;

  // CoefReg_59
  assign CoefData_58 = 16'sb1110110100000101;

  assign CoefOut_58 = CoefData_58;

  // CoefReg_60
  assign CoefData_59 = 16'sb1111011101100111;

  assign CoefOut_59 = CoefData_59;

  // CoefReg_61
  assign CoefData_60 = 16'sb0000001100110011;

  assign CoefOut_60 = CoefData_60;

  // CoefReg_62
  assign CoefData_61 = 16'sb0000110000110001;

  assign CoefOut_61 = CoefData_61;

  // CoefReg_63
  assign CoefData_62 = 16'sb0000111110111000;

  assign CoefOut_62 = CoefData_62;

  // CoefReg_64
  assign CoefData_63 = 16'sb0000110101001101;

  assign CoefOut_63 = CoefData_63;

  // CoefReg_65
  assign CoefData_64 = 16'sb0000011010000011;

  assign CoefOut_64 = CoefData_64;

  // CoefReg_66
  assign CoefData_65 = 16'sb1111111000111110;

  assign CoefOut_65 = CoefData_65;

  // CoefReg_67
  assign CoefData_66 = 16'sb1111011110011100;

  assign CoefOut_66 = CoefData_66;

  // CoefReg_68
  assign CoefData_67 = 16'sb1111010011100111;

  assign CoefOut_67 = CoefData_67;

  // CoefReg_69
  assign CoefData_68 = 16'sb1111011011100010;

  assign CoefOut_68 = CoefData_68;

  // CoefReg_70
  assign CoefData_69 = 16'sb1111110010101001;

  assign CoefOut_69 = CoefData_69;

  // CoefReg_71
  assign CoefData_70 = 16'sb0000010000010110;

  assign CoefOut_70 = CoefData_70;

  // CoefReg_72
  assign CoefData_71 = 16'sb0000101010010110;

  assign CoefOut_71 = CoefData_71;

  // CoefReg_73
  assign CoefData_72 = 16'sb0000111000000011;

  assign CoefOut_72 = CoefData_72;

  // CoefReg_74
  assign CoefData_73 = 16'sb0000110101011111;

  assign CoefOut_73 = CoefData_73;

  // CoefReg_75
  assign CoefData_74 = 16'sb0000100100010000;

  assign CoefOut_74 = CoefData_74;

  // CoefReg_76
  assign CoefData_75 = 16'sb0000001010111000;

  assign CoefOut_75 = CoefData_75;

  // CoefReg_77
  assign CoefData_76 = 16'sb1111110010100010;

  assign CoefOut_76 = CoefData_76;

  // CoefReg_78
  assign CoefData_77 = 16'sb1111100100000001;

  assign CoefOut_77 = CoefData_77;

  // CoefReg_79
  assign CoefData_78 = 16'sb1111100101000111;

  assign CoefOut_78 = CoefData_78;

  // CoefReg_80
  assign CoefData_79 = 16'sb1111110110111100;

  assign CoefOut_79 = CoefData_79;

  // CoefReg_81
  assign CoefData_80 = 16'sb0000010101110100;

  assign CoefOut_80 = CoefData_80;

  // CoefReg_82
  assign CoefData_81 = 16'sb0000111010100100;

  assign CoefOut_81 = CoefData_81;

  // CoefReg_83
  assign CoefData_82 = 16'sb0001011100100011;

  assign CoefOut_82 = CoefData_82;

  // CoefReg_84
  assign CoefData_83 = 16'sb0001110100001001;

  assign CoefOut_83 = CoefData_83;

  // CoefReg_85
  assign CoefData_84 = 16'sb0001111100100101;

  assign CoefOut_84 = CoefData_84;

  // CoefReg_86
  assign CoefData_85 = 16'sb0001110100110100;

  assign CoefOut_85 = CoefData_85;

  // CoefReg_87
  assign CoefData_86 = 16'sb0001011111011011;

  assign CoefOut_86 = CoefData_86;

  // CoefReg_88
  assign CoefData_87 = 16'sb0001000001100001;

  assign CoefOut_87 = CoefData_87;

  // CoefReg_89
  assign CoefData_88 = 16'sb0000100001001100;

  assign CoefOut_88 = CoefData_88;

  // CoefReg_90
  assign CoefData_89 = 16'sb0000000100000001;

  assign CoefOut_89 = CoefData_89;

  // CoefReg_91
  assign CoefData_90 = 16'sb1111101101111010;

  assign CoefOut_90 = CoefData_90;

  // CoefReg_92
  assign CoefData_91 = 16'sb1111100000100111;

  assign CoefOut_91 = CoefData_91;

  // CoefReg_93
  assign CoefData_92 = 16'sb1111011011110010;

  assign CoefOut_92 = CoefData_92;

  // CoefReg_94
  assign CoefData_93 = 16'sb1111011101100101;

  assign CoefOut_93 = CoefData_93;

  // CoefReg_95
  assign CoefData_94 = 16'sb1111100011100000;

  assign CoefOut_94 = CoefData_94;

  // CoefReg_96
  assign CoefData_95 = 16'sb1111101011000011;

  assign CoefOut_95 = CoefData_95;

  // CoefReg_97
  assign CoefData_96 = 16'sb1111110010010011;

  assign CoefOut_96 = CoefData_96;

  // CoefReg_98
  assign CoefData_97 = 16'sb1111111000000111;

  assign CoefOut_97 = CoefData_97;

  // CoefReg_99
  assign CoefData_98 = 16'sb1111111100000111;

  assign CoefOut_98 = CoefData_98;

  // CoefReg_100
  assign CoefData_99 = 16'sb1111111110011100;

  assign CoefOut_99 = CoefData_99;

  // CoefReg_101
  assign CoefData_100 = 16'sb1111111111100100;

  assign CoefOut_100 = CoefData_100;

endmodule  // FilterCoef

