// -------------------------------------------------------------
// 
// File Name: C:\Users\nievep\Downloads\Advanced VLSI Design\Project 1\REPO\Advanced-VLSI-Project-REPO\Project 1\MatlabFilterCalculation\codegen\LowpassFilter\hdlsrc\LowpassFilter.v
// Created: 2025-02-25 23:37:05
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// dataOut                       ce_out        1
// validOut                      ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LowpassFilter
// Source Path: LowpassFilter
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LowpassFilter
          (clk,
           reset,
           clk_enable,
           dataIn,
           validIn,
           ce_out,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  ce_out;
  output  signed [34:0] dataOut;  // sfix35_En32
  output  validOut;


  wire signed [34:0] varargout_1;  // sfix35_En32
  wire varargout_2;


  // Generated by HDL IP Designer.
  dsphdl_FIRFilter u_dsphdl_FIRFilter (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .dataIn(dataIn),  // sfix16_En15
                                       .validIn(validIn),
                                       .dataOut(varargout_1),  // sfix35_En32
                                       .validOut(varargout_2)
                                       );

  assign dataOut = varargout_1;

  assign validOut = varargout_2;

  assign ce_out = clk_enable;

endmodule  // LowpassFilter

