function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 25-Feb-2025 21:30:34

persistent Hd;

if isempty(Hd)
    
    N     = 100;   % Order
    Fpass = 0.2;   % Passband Frequency
    Fstop = 0.23;  % Stopband Frequency
    Astop = 80;    % Stopband Attenuation (dB)
    
    h = fdesign.lowpass('n,fp,fst,ast', N, Fpass, Fstop, Astop);
    
    Hd = design(h, 'equiripple');
    
    set(Hd, 'Arithmetic', 'fixed', ...
        'InputWordLength', 16, ...
        'InputFracLength', 15, ...
        'CoeffWordLength', 16, ...
        'CoeffAutoScale', true, ...
        'FilterInternals', 'Fullprecision');
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

